### ISSUE TITLE
Add dataset source url in doc comments.

### ISSUE THREAD

**Issue by Zrealshadow** [snap-stanford/relbench#108]
Hi,

Thx for your good work.

it seems you add some more datasets except for the original two `rel-stock` and `rel-amazon`.

I'm wondering what's the source of this dataset such as "trial" and "fake". I used these datasets and I have to cite the original source.

Personally, it will be better to add the dataset source url in its corresponding class doc string.

**Comment by kexinhuang12345** [comment]
Hi! The trial dataset is work in progress. so task formulations maybe changed. The dataset source is from https://aact.ctti-clinicaltrials.org/. the fake database is for testing purposes not for building models.
