### ISSUE TITLE
error in rel-event dataset

### ISSUE THREAD

**Issue by rishabh-ranjan** [snap-stanford/relbench#183]
`dataset = get_dataset("rel-event", process=True)`

gives the following error:

![image](https://github.com/snap-stanford/relbench/assets/9881960/fce9d756-e904-40ea-93dc-02c5c14ef9b1)

please see

**Comment by yiweny** [comment]
@rishabh-ranjan Did you upload the zip file to the database?

**Comment by rishabh-ranjan** [comment]
not yet. the usual workflow we have is that `process=True` should be able to create the Database object, and then I upload it. This ensures that the processing the dataset from raw sources is reproducible.

**Comment by rishabh-ranjan** [comment]
I have asked Kexin to upload the zip files you shared. But it will be good if `process=True` works without error too, thanks!

**Comment by yiweny** [comment]
Which version of python are you using? I am using `Python 3.10.13` and I have no problem running this line, `dataset = get_dataset("rel-event", process=True)` after I deleted all data files and re-downloaded the zip.

**Comment by rishabh-ranjan** [comment]
Python 3.8 because we decided to support 3.8 onwards. If pandas version is relevant, I am using pandas 2.0.3.
