### ISSUE TITLE
make lightgbm_link_baseline memory efficient

### ISSUE THREAD

**Issue by rishabh-ranjan** [snap-stanford/relbench#192]
there is a join operation going on here

```
# Include src and dst entity table features for `test_df`
test_df = pd.merge(
    test_df,
    src_entity_df,
    how="left",
    left_on=left_entity,
    right_on=src_entity_table.pkey_col,
)
test_df = test_df.explode(right_entity)
test_df = pd.merge(
    test_df,
    dst_entity_df,
    how="left",
    left_on=right_entity,
    right_on=dst_entity_table.pkey_col,
)
```

this step is basically making a really massive df

instead of a row having (src, list_of_dst) it will make a row for each src, dst for dst in  list_of_dst

this leads to memory issues (e.g. rel-amazon/user-item-rate takes ~200G memory, most runs just fail with memory error)

i think this can be solved with negative sampling of the rows, but will need some thought. please look into it, thanks!

**Comment by XinweiHe** [comment]
I think one way to resolve this is to instead of sample only on the src entities, we could sample on both src and dst entities instead, since we expand the train table into a list of src entity dst entity pairs during training.

**Comment by XinweiHe** [comment]
Additionally, it is likely we need to sample validation table as well to further reduce memory usage.

**Comment by rishabh-ranjan** [comment]
I would think of constructing the table like this:
* use all (src, dst) pairs for which there is a link (positive pairs)
* use sampling for (src, dst) pairs without link (negative sampling)
I think negative sampling is used in other parts of the codebase too, so you can look at the implementation. The sampling strategy can possibly be a commandline arg to the script.

@weihua916 what do you think?

**Comment by XinweiHe** [comment]
@rishabh-ranjan I think we are already doing that in the lightgbm implementation https://github.com/snap-stanford/relbench/blob/main/examples/lightgbm_link_baseline.py#L131

**Comment by rishabh-ranjan** [comment]
ah, i see!
