### ISSUE TITLE
Update on RELBENCH Documentation Needed

### ISSUE THREAD

**Issue by Yuuuuuuu1328** [snap-stanford/relbench#232]
Dear RELBENCH Team,

I hope this message finds you well. I am reaching out to bring to your attention an issue regarding the documentation for RELBENCH, specifically concerning the README file.

I recently noticed that the RELBENCH version has been updated, bringing with it several improvements and new features, which I commend the team for. However, upon reviewing the README documentation, I observed that it has not been synchronized with the latest changes in the package. More specifically, the instructions for acquiring datasets and performing certain operations appear to be outdated.

I found that following the procedures outlined in the current README leads to discrepancies and issues that prevent successful execution. Fortunately, I discovered that the templates provided in the Google Colab notebooks for RELBENCH reflect the correct methodology for working with the updated package. By adhering to the guidelines within these templates, I was able to successfully retrieve datasets and conduct the necessary operations without any hindrance.

Given the importance of up-to-date documentation for users seeking to integrate RELBENCH into their workflows, I kindly request that the README file be revised to align with the current version of the package. This would ensure that all users have clear and accurate instructions, preventing confusion and saving them from unnecessary troubleshooting.

Thank you for your attention to this matter. Your efforts in maintaining and improving RELBENCH are greatly appreciated, and I look forward to seeing the documentation updated to match the excellence of the software itself.

Best regards,

Yu

**Comment by rishabh-ranjan** [comment]
Thanks for your feedback @Yuuuuuuu1328. The README is now up-to-date. Sorry for the delay on our side. We are working towards releasing v1.0.0 officially, and getting everything synced up as we go along.
