### ISSUE TITLE
Error when running script

### ISSUE THREAD

**Issue by Yuuuuuuu1328** [snap-stanford/relbench#237]
Dear relbench team,

python gnn_node.py --dataset rel-f1 --task driver-position

`Traceback (most recent call last):
  File "gnn_node.py", line 70, in <module>
    data, col_stats_dict = make_pkey_fkey_graph(
  File "\relbench\modeling\graph.py", line 83, in make_pkey_fkey_graph
    to_unix_time(table.df[table.time_col])
  File "\relbench\modeling\utils.py", line 14, in to_unix_time
    unix_time = ser.astype(int).values
`

`    raise TypeError(
TypeError: Converting from datetime64[ns] to int32 is not supported. Do obj.astype('int64').astype(dtype) instead
`

**Comment by Yuuuuuuu1328** [comment]
`unix_time = ser.astype('int64').values` **works**

I've been working closely with your RelBench framework, specifically version 1.0.0, and I've noticed an area where a slight enhancement could potentially improve the user experience.

There seems to be a detail that requires attention, and I believe addressing it would make the framework even more robust and user-friendly. If possible, I'd recommend considering this refinement in an upcoming update.

Additionally, I've observed that when using versions other than 1.0.0, there are minor issues that crop up, which might be related to compatibility or changes in the API. To help prevent confusion for future users, I suggest updating the README file to clearly indicate any known compatibility constraints or recommended version ranges. This could include specifying that certain features or bug fixes are exclusive to version 1.0.0 or later.

By keeping the documentation up-to-date with such information, new adopters of RelBench can have a smoother onboarding process and avoid potential pitfalls early on in their projects.

Thank you for developing such a valuable tool for the community. Your work is greatly appreciated, and I'm looking forward to seeing how RelBench evolves in the future.

**Comment by yiweny** [comment]
Hi @Yuuuuuuu1328 I cannot reproduce your problem. What are your package versions? Mine is the following
```
Pandas version: 1.5.2, NumPy version: 1.26.0
```

**Comment by Yuuuuuuu1328** [comment]
`pandas                     2.0.3，numpy                      1.23.5`

Thank you very much for your reply. Here's my version.

**Comment by Yuuuuuuu1328** [comment]
> Hi @Yuuuuuuu1328 I cannot reproduce your problem. What are your package versions? Mine is the following
> 
> ```
> Pandas version: 1.5.2, NumPy version: 1.26.0
> ```

Pandas version: **2.0.3** , NumPy version: **1.23.5**

Thank you very much for your reply. Here's my version.

**Comment by yiweny** [comment]
Can you degrade the pandas version and see if the code works by default?

**Comment by rishabh-ranjan** [comment]
Pandas version: 2.0.3 and Numpy 1.24.4 works on my end
