### ISSUE TITLE
`AttributeError: 'AvitoDataset' object has no attribute 'get_task'`

### ISSUE THREAD

**Issue by akihironitta** [snap-stanford/relbench#249]
The following code snippet from https://relbench.stanford.edu/databases/avito/:
```python
from relbench.datasets import get_dataset
dataset = get_dataset("rel-avito")
task = dataset.get_task("ad-ctr")
```
fails with an error:
```
Traceback (most recent call last):
  File "/path/to/file.py", line 38, in <module>
    task = dataset.get_task("ad-ctr")
AttributeError: 'AvitoDataset' object has no attribute 'get_task'
```

The version I use is `1.1.0`.

**Comment by rishabh-ranjan** [comment]
That URL is outdated and will be removed soon. Please see instructions on the Github README or the Start page of the website for loading tasks.

**Comment by akihironitta** [comment]
Hi @rishabh-ranjan, This is still an issue. Mind updating the website to avoid confusion?
