### ISSUE TITLE
Dataset `rel-stack` with task `user-post-related` doesn't exist

### ISSUE THREAD

**Issue by akihironitta** [snap-stanford/relbench#258]
It should instead be:

```diff
- user-post-related
+ post-post-related
```

<img width="1040" alt="image" src="https://github.com/user-attachments/assets/3922b650-caab-453c-9cfe-174cd071eb09">

https://relbench.stanford.edu/datasets/rel-stack/

**Comment by rishabh-ranjan** [comment]
Thanks for reporting! @kexinhuang12345 can you please update?

**Comment by kexinhuang12345** [comment]
just updated!
