### ISSUE TITLE
Speed up downloading datasets via multiple connections

### ISSUE THREAD

**Issue by akihironitta** [snap-stanford/relbench#265]
Since the default way is too slow (at 5~15 MB/s from an AWS us-west-2 instance), I manually downloaded files using an external tool (https://github.com/aria2/aria2):

```console
$ aria2c -x 16 -d ~/.cache/relbench/rel-amazon/ https://relbench.stanford.edu/download/rel-amazon/db.zip
```

Haven't done research on other options, it'd be nice to consider supporting something like this.

**Comment by rishabh-ranjan** [comment]
Thanks. Added to the README.
