### ISSUE TITLE
Lower Than Expected Scores When Reproducing H&M Recommendation Task Results

### ISSUE THREAD

**Issue by DanialNejad** [snap-stanford/relbench#271]
I have been trying to reproduce the results of the recommendation task on the H&M dataset as outlined in the associated paper, but so far, I have been getting significantly lower scores than reported. I have followed the instructions and steps provided in the documentation and paper, using the specified hyperparameters and dataset.

Steps Taken:
git clone https://github.com/snap-stanford/relbench
cd relbench/examples
python idgnn_link.py --dataset rel-hm --task user-item-purchase

Despite following these steps, the scores I’m getting are consistently lower than the ones reported in the paper. I suspect that there might be additional details or steps not mentioned explicitly in the paper that could be affecting the results.

**Comment by adobles96** [comment]
Hey Danial, I just checked on my end and was able to reproduce the numbers from the paper. What numbers are you getting exactly? One small detail to keep in mind is that the paper reports MAP as a percentage (2.64%) whereas the script just prints out the proportion (0.0264).

**Comment by DanialNejad** [comment]
Hi Alejandro,

Oh, I hadn't considered that it was reported as a percentage. Thanks for
pointing that out and for your response! I appreciate the clarification.

Best regards,
Danial
