### ISSUE TITLE
Issue with running `train_model.ipynb` in Colab

### ISSUE THREAD

**Issue by cpondoc** [snap-stanford/relbench#274]
I'm working on a Relbench tutorial for the class CS 224W. I tried running the `train_model.ipynb` Colab but unfortunately got a common error across PyG:
```
'NeighborSampler' requires either 'pyg-lib' or 'torch-sparse'
```

After perusing through several threads on the issue, it appears as though it has something to do with [installing certain dependencies](https://github.com/pyg-team/pytorch_geometric/discussions/9143) (i.e., `torch_scatter`, `torch_sparse`) prior to installing `torch_geometric`. Using these tips, I was able to debug and get a version running locally (using a standalone Conda environment) as well on Colab (which I've made public [here](https://github.com/pyg-team/pytorch_geometric/discussions/9143)). Happy to make the PR but just thought I'd bring up the issue first!

cc @JosephGuman

**Comment by rishabh-ranjan** [comment]
Thanks for your efforts. A PR would be appreciated!
