### ISSUE TITLE
rel-stack embedding fails

### ISSUE THREAD

**Issue by goelzva** [snap-stanford/relbench#282]
Hi, I have the following issue that I can't resolve myself:

Everytime I try to run gnn_node.py with --dataset rel-stack, the run fails and I get a numpy error.
![image](https://github.com/user-attachments/assets/00ab0043-3eec-4d10-9b21-6e47046d5f86)

All other benchmarks work without a problem. The error happens somewhere in Dataset, compute_col_stats. Have you encountered this before?

**Comment by rishabh-ranjan** [comment]
@yiweny we had some problem with the numpy version earlier, do you think this is related? Can you help?

**Comment by goelzva** [comment]
Hi all, any update here?

**Comment by rishabh-ranjan** [comment]
@yiweny can you please take a look?

**Comment by goelzva** [comment]
Hi everyone, I looked into it again and found the error. In rel-stack, table "badges", the column "TagBased" is supposed to be stype.categorical, but when loading the stype dict it instead returns stype.numerical. This then leads to the numpy error since Booleans can't be subtracted. I can locally fix it but to solve it for everyone you probably need to fix it in the relbench database. Cheers!

**Comment by rishabh-ranjan** [comment]
Ah, thanks for investigating! We will try to improve the automatic stype detection. But in general, it is likely to have flaws so fixing the column stype manually is the recommended way when something goes wrong, as you have done!
