### ISSUE TITLE
The implementation of HeteroGraphSAGE has no dropout layer ?

### ISSUE THREAD

**Issue by Zrealshadow** [snap-stanford/relbench#283]
Hi,

When I follow the `relbench/tutorials/train_model.ipynb` to run `site-success` regression task in `rel-trail` dataset, I found there is a server over-fitting problem. 

I noticed the model, HeteroGraphSAGE employed in `relbench/tutorials/train_model.ipynb` has no dropout layer for regularization.

https://github.com/snap-stanford/relbench/blob/6bcb12a94b163c52e01cc272dfd4817cd13eff69/relbench/modeling/nn.py#L168-L171

I just wonder is it correct ?

**Comment by rishabh-ranjan** [comment]
yes, but you can try to add a dropout layer and see if that helps
