### ISSUE TITLE
Create New Class to Support Custom non-GNN Architectures?

### ISSUE THREAD

**Issue by cpondoc** [snap-stanford/relbench#286]
When looking at the definition of the GNN architecture in RDL, we specify a specific type of GNN layer – in particular, a `SAGEConv` layer – when defining each of the convolutional layers:

```python
self.convs = torch.nn.ModuleList()
for _ in range(num_layers):
    conv = HeteroConv(
        {
            edge_type: SAGEConv((channels, channels), channels, aggr=aggr)
            for edge_type in edge_types
        },
        aggr="sum",
    )
    self.convs.append(conv)
```

With the GNN architecture being one of the critical parts of RDL, though, we think there is an opportunity to have users specify their own GNN layer. We think this could look something like a `HeteroGraphCustom` layer, with a constructor that looks similar to `HeteroGraphSAGE` but that takes in a PyG GNN layer (namely, a `MessagePassing` interface):

```python
class HeteroGraphCustom(torch.nn.Module):
    def __init__(
        self,
        node_types: List[NodeType],
        edge_types: List[EdgeType],
        channels: int,
        aggr: str = "mean",
        num_layers: int = 2,
	conv_layer: MessagePassing = SAGEConv,
    ):
```

We believe this new class could help enable quicker iteration and further exploration on RDL architectures.

cc @JosephGuman @merceod

**Comment by rishabh-ranjan** [comment]
We welcome a PR for this.
