### ISSUE TITLE
Clinical trial relational database

### ISSUE THREAD

**Issue by kexinhuang12345** [snap-stanford/relbench#60]
Proposed by Sergiusz Wesolowski. A public database on clinical trials http://aact.ctti-clinicaltrials.org/. here is the schema: https://aact.ctti-clinicaltrials.org/schema

**Comment by Wesserg** [comment]
Hello - I would be very happy to contribute to this. I am playing with this data and GNNs as a side project.

**Comment by rishabh-ranjan** [comment]
This has been added to RelBench as rel-trial.
