### ISSUE TITLE
Can't get the dataset as the example indicates

### ISSUE THREAD

**Issue by gkarozis** [snap-stanford/relbench#68]
I am trying to run the example of getting the 'rel-stackex' dataset, but an error occurs:

SSLError: HTTPSConnectionPool(host='relbench.stanford.edu', port=443): Max retries exceeded with url: /staging_data/rel-amazon-books_5_core/db.zip (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

Could you please help me overcome this issue?

Thanks in advance!

**Comment by kexinhuang12345** [comment]
That is weird, can you share the scripts to reproduce the error?

**Comment by gkarozis** [comment]
![Screenshot_167](https://github.com/snap-stanford/relbench/assets/48602908/1195fc74-b4d3-4cbe-acf4-f2b0d5d8f5e1)

**Comment by gkarozis** [comment]
![Screenshot_168](https://github.com/snap-stanford/relbench/assets/48602908/561944f7-3776-4b3b-9a5a-e02e17a0befd)

**Comment by kexinhuang12345** [comment]
I just tried it and it works. looks like the error involves your local machine.

![image](https://github.com/snap-stanford/relbench/assets/27795075/09ab7c05-2325-445a-96f1-bc0f8564518f)

**Comment by kexinhuang12345** [comment]
@rishabh-ranjan @rusty1s @weihua916 any idea on why this happens?

**Comment by rishabh-ranjan** [comment]
We have updated the repo significantly. Please try again with the new instructions.
