### ISSUE TITLE
Question: Learning Embedding vectors

### ISSUE THREAD

**Issue by pmavrodiev** [snap-stanford/relbench#72]
Section 3.4.1 of the paper describes *Heterogeneous Message Passing* as a generic framework to learn embedding vectors $\{{h_{v}^{(L)}\}}_{\nu \in V}$ for each node, which are then fed to the model heads.

Do you intend to offer an implementation of the heterogeneous message passing in this package?

**Comment by kexinhuang12345** [comment]
Yes! RelBench is currently in beta version. We will provide baseline implementations in a few months.

**Comment by rishabh-ranjan** [comment]
Please see examples directory for the GNN training scripts.
