### ISSUE TITLE
Version compatibility for Python 3.12

### ISSUE THREAD

**Issue by xiaohaoxing** [snap-stanford/relbench#74]
I've made a conda environment based on Python=3.12.0, then I ran `pip install relbench` and failed with an error like: `ERROR: Could not build wheels for duckdb, which is required to install pyproject.toml-based projects`.

It's caused by a lack of support for Python 3.12 in DuckDB 0.9.2(refer to [StackOverFlow](https://stackoverflow.com/questions/77693728/failed-building-wheel-for-duckdb)), can easily fixed with execute **`pip install duckdb --upgrade --pre`** before `pip install relbench`.

**Comment by rishabh-ranjan** [comment]
Thanks for reporting. From your StackOverflow link: "It will be included in version 0.10.0, released in a few weeks."

We will just wait for duckdb to support 3.12 in an official release. Meanwhile, folks can use the pip install workaround you mentioned or stick with an older python version.
