### ISSUE TITLE
Should `posts.AcceptedAnswerId` be a Foreign Key?

### ISSUE THREAD

**Issue by toenshoff** [snap-stanford/relbench#80]
The column `posts.AcceptedAnswerId` in `rel-stackex` is currently used as a numerical feature but seems to be a foreign key reference to `comments.id`.

**Comment by kexinhuang12345** [comment]
great catch - we will add this foreign key in the next release!

**Comment by weihua916** [comment]
Fixed in https://github.com/snap-stanford/relbench/pull/84
